# Part 1. Warm up

# 1.

In [1]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
reshaped_a = a.reshape(2, 4)

print(reshaped_a)

[[1 2 3 4]
 [5 6 7 8]]


# 2.

In [2]:
import torch

# Define the tensors
a = torch.tensor([1,3,5,6])
b = torch.tensor([5,6,8,9])

print(f'a is {a}\nb is {b}')

a is tensor([1, 3, 5, 6])
b is tensor([5, 6, 8, 9])


In [3]:
addition = a + b
addition

tensor([ 6,  9, 13, 15])

In [4]:
multiplication = a * b
multiplication

tensor([ 5, 18, 40, 54])

In [5]:
power = a ** b
power

tensor([       1,      729,   390625, 10077696])

In [6]:
dot = torch.dot(a,b)
dot

tensor(117)

In [7]:
exponential_a = torch.exp(a)
log_b = torch.log(b)
dot_product_exponential_log = torch.dot(exponential_a, log_b)
dot_product_exponential_log

tensor(1235.4036)

# 3.

* (a)

In [8]:
x_val = 5
y_val = 6
z_val = 8
k_val = 9

# Create tensors with the values, specify requires_grad=True
x = torch.tensor([x_val], dtype=torch.float32, requires_grad=True)
y = torch.tensor([y_val], dtype=torch.float32, requires_grad=True)
z = torch.tensor([z_val], dtype=torch.float32, requires_grad=True)
k = torch.tensor([k_val], dtype=torch.float32, requires_grad=True)

g = torch.exp(x) * x**2 + 3 * torch.exp(y) * y**2 + 5 * torch.exp(z) * z**2 + 6 * torch.exp(k) * k**2

g.backward()

gradient_x = x.grad
gradient_y = y.grad
gradient_z = z.grad
gradient_k = k.grad

print(f'Gradient of x is {gradient_x.item()}')
print(f'Gradient of y is {gradient_y.item()}')
print(f'Gradient of z is {gradient_z.item()}')
print(f'Gradient of k is {gradient_k.item()}')

Gradient of x is 5194.4609375
Gradient of y is 58093.75
Gradient of z is 1192383.25
Gradient of k is 4813232.0


* (b)

In [9]:
A_ = [[4,3],[7,9]]
B_ = [[3,5],[1,11]]

A = torch.tensor(A_, dtype=torch.float32, requires_grad=True)
B = torch.tensor(B_, dtype=torch.float32)

f_A = torch.log(torch.norm(torch.matmul(torch.matmul(torch.matmul(torch.matmul(torch.matmul(torch.matmul(A.T, A), B.T), A), A.T), A), B),p=2)**2)

f_A.backward()

gradient_A = A.grad

print(gradient_A)


tensor([[0.1737, 0.2854],
        [0.3837, 0.6404]])


* (c)

In [10]:
x_val = 3
y_val = 7

x = torch.tensor([x_val], dtype=torch.float32,requires_grad=True)
y = torch.tensor([y_val], dtype=torch.float32,requires_grad=True)

F = torch.tanh(x) + torch.tanh(y)

F.backward()

gradient_x = x.grad
gradient_y = y.grad

print(f'Gradient at the point\n(x = 3, y = 7) is ({gradient_x.item()}, {gradient_y.item()})'
    )

Gradient at the point
(x = 3, y = 7) is (0.009865999221801758, 3.337860107421875e-06)


# 4.

(1)

In [11]:
a = torch.tensor([1,2,3], dtype=int)

b = a.numpy()

a_float = a.float()


In [12]:
b

array([1, 2, 3])

(2)

In [13]:
a_float

tensor([1., 2., 3.])

# 5.

(1)

In [14]:
a = np.array([[1,3,5],[2,1,5]])
b = np.array([[8,4],[3,6],[2,7]])

dot = np.dot(a,b)

dot

array([[27, 57],
       [29, 49]])

(2)

In [15]:
a = np.array([[100,2,1]])

f_n = np.linalg.norm(a, 'fro')

f_n

100.024996875781